name: Weekly Mealprep

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  mealprep:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install --break-system-packages -r requirements.txt

      - name: Run mealprep script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        run: python3 main.py
